### ISSUE TITLE
graphassets.com cert issues

### ISSUE THREAD

**Issue by bendera** [christian-bromann/bromann.dev#13]
Hi,

Something went wrong with the cert of the graphassets.com site. I don't know if you owned the domain, but a [demo.gif](https://media.graphassets.com/Jc6sNwiQAGCZ50f9JkSj) hosted on this URL appeared in your article about VSCode extension testing. (It's a great article btw., thank you for sharing it!)

I'm using a work laptop now where the browser settings are managed by my organization, so I'm not sure if this error occurs elsewhere.

![image](https://user-images.githubusercontent.com/3748508/215817003-894c6c62-1c83-40f0-9d18-328457d9a28f.png)

**Comment by christian-bromann** [comment]
Thanks for reporting, I will try to replace the image.
